apiVersion: v1
kind: Service
metadata:
  name: simple-aspnet-app-svc
  labels:
    version: test
spec:
  selector:
    app: simple-aspnet-app
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer