name: CI
on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.DOCKER_REGISTRY }}  
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: |
          docker build . -t ${{ secrets.DOCKER_REGISTRY }}/simpleaspnetcorewebapp:${{ github.sha }}
          docker push ${{ secrets.DOCKER_REGISTRY }}/simpleaspnetcorewebapp:${{ github.sha }}
